### ISSUE TITLE
temp_user workaround

### ISSUE THREAD

**Issue by elias-summermatter** [wepublish/wepublish#522]
Remove and cleanup the temp_user workaround

**Comment by roosnic1** [comment]
@elias-summermatter could you please elaborate what you mean with that?

**Comment by michael-scheurer** [comment]
When the registerAndReceivePayment mutation fails, it creates a temp_<timestamp><email> user but the database is never cleaned up.

In my opinion:
- the api should register failed attempts to register so that admins can see failures and act accordingly.
- the api should allow to register multiple subscriptions per user, even when the mail already exists.
- the api should not create tmp_user mails.
